### ISSUE TITLE
Better peptide length error handling

### ISSUE THREAD

**Issue by julia326** [openvax/mhctools#106]
There are some uncaught errors resulting from trying to predict binding for peptides that are too short or empty, and we should handle those better.

**Comment by iskandr** [comment]
Interesting -- do you have a test case that isn't caught by `_check_peptide_lengths`?

**Comment by julia326** [comment]
@armish wrote up some cases at https://github.com/hammerlab/vaxrank/pull/132. This is also related to that time we were passing in an empty peptide (https://github.com/hammerlab/isovar/issues/85).

**Comment by iskandr** [comment]
"MVYI" -- we're not currently specifying min lengths for any of the NetMHC predictors. I'm guessing it's 7 or 8 but we need to check for all of them.

**Comment by iskandr** [comment]
The empty protein product hitting the same error is mysterious though, wouldn't it get caught by the default min peptide length of 1?

**Comment by julia326** [comment]
Weirdly no, which is why we hit that AssertionError much later

**Comment by iskandr** [comment]
I might be wrong but I think that @armish's example of `topiary --mhc-predictor netmhccons --mhc-alleles HLA-A02:01 --genome GRCh37 --variant 3 53925802 G T --mhc-epitope-lengths 9` results in no peptides (rather than empty peptides).

**Comment by iskandr** [comment]
Yep, I just printed `peptide_list` in `mhctools.BasePredictor` and got `[]`. A truncated protein sequence has no 9mers.
