### ISSUE TITLE
MHCflurry should raise UnsupportedAllele

### ISSUE THREAD

**Issue by iskandr** [openvax/mhctools#129]
Currently you can build a `MHCflurry` instance with any alleles but it will raise a `ValueError` after a call to predict if that allele is unsupported. The other predictors will instead raise `UnsupportedAllele` at the time of construction, which `MHCflurry` should do as well.

**Comment by iskandr** [comment]
@timodonnell How do you check if an allele is supported by MHCflurry?

**Comment by timodonnell** [comment]
@iskandr you can use the `supported_alleles` property on a `Class1AffinityPredictor` https://openvax.github.io/mhcflurry/api.html#mhcflurry.Class1AffinityPredictor.supported_alleles

**Comment by iskandr** [comment]
Fixed by https://github.com/openvax/mhctools/pull/131
