### ISSUE TITLE
NetMHCpan4

### ISSUE THREAD

**Issue by iskandr** [openvax/mhctools#133]
It looks like the NetMHCpan3 class is working fine with NetMHCpan 4.0 but it's confusing to have the wrong version in the name of the class. We should either add a NetMHCpan4 class or rename the other classes for NetMHCpan to something like NetMHCpan_legacy_28

**Comment by timodonnell** [comment]
This was done in #126 - added NetMHCpan4 class. Or is that not what you mean?
