### ISSUE TITLE
how to install api not in mhctools

### ISSUE THREAD

**Issue by worker000000** [openvax/mhctools#138]
from mhctools import NetMHCpan
predictor = NetMHCpan(alleles=["A*02:01", "hla-a0101"])

this wiill raise error "FileNotFoundError: [Errno 2] No such file or directory: 'netMHCpan': 'netMHCpan'"

and I tried to download the api file, where should I put the file for mhctools to know where the api is
thanks a lot

**Comment by iskandr** [comment]
Hey @2236529177 -- you have to download and install the NetMHCpan tool from http://www.cbs.dtu.dk/cgi-bin/nph-sw_request?netMHCpan
