### ISSUE TITLE
Multiple processes for NetMHC and NetMHCpan

### ISSUE THREAD

**Issue by tavinathanson** [openvax/mhctools#15]
From @iskandr, we should check this:

> I think that NetMHC and NetMHCpan don't allow you to specify a distinct temp directory for each process, which is why I didn't use multiple processes for them. I need to check if that's actually true.

And based on that, decide if we can also split NetMHC and NetMHCpan runs into multiple processes.

**Comment by tavinathanson** [comment]
From @iskandr:

> @tavinathanson I checked the commandline flags and both NetMHCpan and NetMHCcons allow you to specify the tempdir (NetMHCcons commandline flags). I'm suspicious that internally it only passes that flag to -tdir flag to NetMHCpan and not NetMHC (which would cause weird bugs when running multiple predictors concurrently). Let's remember this thread if NetMHCcons causes us trouble later?

**Comment by tavinathanson** [comment]
@iskandr I guess I misunderstood your concern. So you're talking about `NetMHCcons`'s usage of `NetMHC` and `NetMHCpan`? But you had cons split into multiple processes already; does my PR #12 (which just adds flexibility to that) introduce a new concern?

**Comment by iskandr** [comment]
Sorry, I misunderstood the PR. I think it's fine.

**Comment by kippakers** [comment]
Hey @tavinathanson, ideally I want to run topiary with 6 alleles \* 5 peptide lengths and mhc-cons which can spin out 100+ processes (and that's too many for my system).  Does this addition to mhctools allow me to set an upper limit on mhc-cons children that will run at once?  If so, how do I implement setting such a limit?

**Comment by tavinathanson** [comment]
Hey @kippakers, yup! Does setting `process_limit` in the `NetMHCcons` constructor work for you? Looks like I should add this to the README and add some better comments!

**Comment by kippakers** [comment]
@tavinathanson Yeah, OK that did it, thanks for your help!

**Comment by iskandr** [comment]
@tavinathanson I think that with my refactoring, all of the predictors that can run in parallel do-- should I close this issue?

**Comment by tavinathanson** [comment]
Agreed, closing it out
