### ISSUE TITLE
Mhcflurry 1.6.0 support

### ISSUE THREAD

**Issue by Stikus** [openvax/mhctools#150]
Hello.
Does current release of `mhctools` support `mhcflurry 1.6.0`?
This [line](https://github.com/openvax/mhctools/blob/master/setup.py#L65) causing dependency errors when installing https://github.com/griffithlab/pVACtools.

Can you confirm existence or nonexistence of support for correct version pins?

**Comment by timodonnell** [comment]
Yes, it is compatible but as you note we have been setting an upper version for mhcflurry in the dependencies. I think it's safe to drop that restriction though (@iskandr , @julia326 let me know if you disagree) - we have been keeping mhcflurry backwards compatible with new releases for some time now. Testing out a branch that drops the version restriction, will push a new release of mhctools once I confirm that nothing breaks.
