### ISSUE TITLE
Add support for mhcflurry 2.0 ?

### ISSUE THREAD

**Issue by pl618** [openvax/mhctools#156]
mhcflurry 2.0:
https://www.sciencedirect.com/science/article/pii/S2405471220302398
https://github.com/openvax/mhcflurry

**Comment by iskandr** [comment]
@timodonnell Want to do it or should I?

**Comment by timodonnell** [comment]
@iskandr Go for it, thanks - mostly should just be a matter of bumping the version dependency. Let me know if you hit any issues.

**Comment by iskandr** [comment]
Cool, I'll give it a shot and see if anything breaks.

**Comment by iskandr** [comment]
Should be working, let me know if you encounter any problems.

**Comment by pl618** [comment]
@iskandr  thank you. The mhcflurry 2.0 output several columns more than older mhcflurry. The columns are "allele,peptide,mhcflurry_affinity,mhcflurry_affinity_percentile,mhcflurry_processing_score,mhcflurry_presentation_score,mhcflurry_presentation_percentile", in particular, "mhcflurry_processing_score,mhcflurry_presentation_score,mhcflurry_presentation_percentile" is new thing and is more usefull. Should MHCtools add these results? thanks!
