### ISSUE TITLE
Mash together DQA1/DQB1 alleles

### ISSUE THREAD

**Issue by kippakers** [openvax/mhctools#33]
So netmhciipan takes DQ and DP alleles in the following format:

HLA-DPA10401-DPB19901
HLA-DQA10101-DQB10201

It would be great if mhctools could take an mhcfile with 2 DQA1 alleles and 2 DQB1 alleles and mash them up into the above format.  
eg:

```
DQA1*03:02
DQA1*01:02
DQB1*06:11
DQB1*03:03
```

becomes:

```
HLA-DQA10302-DQB10611,HLA-DQA10302-DQB10303,HLA-DQA10102-DQB10611,HLA-DQA10102-DQB10303
```

**Comment by iskandr** [comment]
@tavinathanson @kippakers I guess to get started we can limit this functionality to just the netmhciipan predictor, though once we add another class II model we'll have to generalize it.

**Comment by iskandr** [comment]
I think we'll leave it up to the user to determine the pairing, since not all alpha & beta chains are compatible.
