### ISSUE TITLE
the 'fasta_dictionary' argument to a predictor's `predict` method should be renamed

### ISSUE THREAD

**Issue by timodonnell** [openvax/mhctools#43]
Looks like this argument is a dict from arbitrary keys to possible epitope protein sequences. The term `fasta_dictionary` seems confusing to me, as I'm not sure what these have to do with fastas, except that they might have come from a fasta. Maybe `peptide_dict`, `possible_epitopes_dict`, or just `peptides` would be clearer

**Comment by timodonnell** [comment]
The semantics are actually to search for all sub-peptides of the protein sequences given. Still a bit confused at the name

**Comment by iskandr** [comment]
`protein_dict`? 

Also, I'm thinking about having a default `predict` just take a list of peptides and have `predict_dict` take a dictionary of name to protein mappings. Thoughts?

**Comment by timodonnell** [comment]
Yeah, I think your idea makes sense. Having a way to just predict for peptides instead of sub-peptides within a longer sequence would be great. The latter should probably have a descriptive name like `predict_for_subsequences`.
