### ISSUE TITLE
NetChop support (proteasome cleavage prediction)

### ISSUE THREAD

**Issue by fbucchini** [openvax/mhctools#51]
Proteasome cleavage is the first step to process antigens: exogenous proteins are cut in small peptides (~9 aminoacids) that are then processed by the immune system. [NetChop](http://www.cbs.dtu.dk/services/NetChop/) is a software that predicts where the cleavage is likely to happen.  It might be of interest to add support for `NetChop`, so the whole chain from protein sequences to binding predictions can be handled with `mhctools`. 

A few months ago, I've written quick small script in R that calls the NetChop binary and saves results as tabulated file, for a university project. You can find it [here](https://github.com/fbucchini/igem-evry-pipeline/blob/master/immunity_predictions/proteasome_cleavage.R). It might be helpful to get started !

**Comment by timodonnell** [comment]
Thanks @fbucchini ! This was implemented in #83.
