### ISSUE TITLE
Error message logged when creating NetMHC

### ISSUE THREAD

**Issue by iskandr** [openvax/mhctools#53]
`INFO:root:Skipping allele Unrecognized parameter: -A: Malformed MHC type A`

**Comment by tavinathanson** [comment]
What do you mean "when creating"? Is this a 3.x vs. 4.x issue?

**Comment by iskandr** [comment]
`netmhc = mhctools.NetMHC(alleles=["HLA-A0201"])`

I seem to have NetMHC 4.0:

```
$ netmhc
# /Users/iskander/code/netmhc-bundle/netMHC-4.0/Darwin_x86_64/bin/netMHC
...
```

**Comment by iskandr** [comment]
I seem to have NetMHC 4.0:

```
$ netmhc
# /Users/iskander/code/netmhc-bundle/netMHC-4.0/Darwin_x86_64/bin/netMHC
```

I should have said "instantiating": `netmhc = mhctools.NetMHC(["A0201"])`

**Comment by JPFinnigan** [comment]
This is the same as Topiary https://github.com/hammerlab/topiary/issues/41

**Comment by tavinathanson** [comment]
Thanks @JPFinnigan, I knew it looked familiar!
