### ISSUE TITLE
Does the README example still work?

### ISSUE THREAD

**Issue by arahuja** [openvax/mhctools#8]
Ran the README example (with small edit as curly-braces are wrong currently)

Log lines:

```

INFO:root:netMHCpan -xls -xlsfile /tmp/netMHCpan_outputnbiuow68 -l 9 -f /tmp/peptideoog0vb52 -a HLA-A01:01,HLA-A02:01
INFO:root:netMHCpan finished with return code 0
INFO:root:netMHCpan took 0.0200 seconds
INFO:root:Cleaning up /tmp/netMHCpan_outputnbiuow68
INFO:root:Cleaning up /tmp/peptideoog0vb52
>1L3Y_0
ECDTINCERYNGQVCGGPGRGLCFCGKCRCHPGFEGSACQA
>1L2Y_1
NLYIQWLKDGGPSSGRPPPS
```

Error:

```
ValueError                                Traceback (most recent call last)
<ipython-input-8-0cd0a0e7ebcc> in <module>()
      6 }
      7 
----> 8 epitope_collection = predictor.predict(protein_sequences)
      9 
     10 # flatten binding predictions into a Pandas DataFrame

/demeter/users/ahujaa01/src/hammerlab/mhctools/mhctools/netmhc_pan.py in predict(self, fasta_dictionary, raise_on_error)
     54                 sequence_key_mapping=sequence_key_mapping,
     55                 fasta_dictionary=fasta_dictionary,
---> 56                 prediction_method_name="netmhcpan")
     57 
     58         # TODO(tavi) Unwise to just return an empty DataFrame.

/demeter/users/ahujaa01/src/hammerlab/mhctools/mhctools/file_formats.py in parse_xls_file(xls_contents, sequence_key_mapping, fasta_dictionary, prediction_method_name)
    150     if len(lines) == 0:
    151         raise ValueError("Empty XLS file for %s result" % (
--> 152             prediction_method_name,))
    153 
    154     # top line of XLS file has alleles

ValueError: Empty XLS file for netmhcpan result
```

The example data works for `IedbMhcClass1` Predictor

**Comment by iskandr** [comment]
It works for me. What version of NetMHCpan do you have?

```
In [4]: protein_sequences = {'1L2Y': 'NLYIQWLKDGGPSSGRPPPS',
 '1L3Y': 'ECDTINCERYNGQVCGGPGRGLCFCGKCRCHPGFEGSACQA'}

In [5]: from mhctools import NetMHCpan

In [6]: predictor = NetMHCpan(alleles=["A*02:01", "hla-a0101"])
INFO:root:netMHCpan finished with return code 0
INFO:root:netMHCpan took 0.0671 seconds

In [7]: epitope_collection = predictor.predict(protein_sequences)
>1L2Y_0
NLYIQWLKDGGPSSGRPPPS
>1L3Y_1
ECDTINCERYNGQVCGGPGRGLCFCGKCRCHPGFEGSACQA
INFO:root:netMHCpan -xls -xlsfile /var/folders/77/d7x5zqy96q3c1_l5kd43jsyr0000gn/T/netMHCpan_outputhbbxxhde -l 9 -f /var/folders/77/d7x5zqy96q3c1_l5kd43jsyr0000gn/T/peptide_dg8hcen -a HLA-A01:01,HLA-A02:01
INFO:root:netMHCpan finished with return code 0
INFO:root:netMHCpan took 2.3683 seconds
INFO:root:Cleaning up /var/folders/77/d7x5zqy96q3c1_l5kd43jsyr0000gn/T/netMHCpan_outputhbbxxhde
INFO:root:Cleaning up /var/folders/77/d7x5zqy96q3c1_l5kd43jsyr0000gn/T/peptide_dg8hcen

In [8]: epitope_collection
Out[8]: <EpitopeCollection with 90 elements>
```

**Comment by arahuja** [comment]
I'm using netMHCpan 2.8, are you on a different version? Also, were you able to run it on a Mac? Currently I have running on a dev machine.

**Comment by iskandr** [comment]
I've only tried it on my Macbook, I'll try on a dev box tomorrow, I
wouldn't be surprised if NetMHCpan for Linux has some subtle difference
from the Mac version. Are you able to run the commandline netmhcpan without
mhctools?

**Comment by cat2cat** [comment]
what am I missing here, why it does not work  ? 
from mhctools import NetMHCpan
# Run NetMHCpan for alleles HLA-A*01:01 and HLA-A*02:01
predictor = NetMHCpan(alleles=["A*02:01", "hla-a0101"])

>>> predictor = NetMHCpan(alleles=["A*02:01", "hla-a0101"])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mhctools/netmhc_pan.py", line 43, in NetMHCpan
    stderr=devnull)
  File "/Users/xhu/miniconda2/lib/python2.7/subprocess.py", line 212, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/Users/xhu/miniconda2/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/Users/xhu/miniconda2/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by iskandr** [comment]
Hi @cat2cat, do you have NetMHCpan binaries installed locally? If not you have to use the web-based  IEDB predictors.

**Comment by cat2cat** [comment]
Hi, Alex,
I have downloaded netMHCpan-3.0 and it is in the mhctool, what should I do to install netMHCpan?

Many thanks,
Kathy


mhctools-master xhu$ ls

LICENSE build mhctools pylintrc test

README.md dist mhctools.egg-info requirements.txt

RELEASING.md lint.sh netMHCpan-3.0 setup.py


mhctools-master xhu$ ls netMHCpan-3.0/

Linux_x86_64 data.tar.gz netMHCpan-3.0.readme test

data netMHCpan netMHCpan.1

**Comment by iskandr** [comment]
Is NetMHCpan in your path? Are you able to run it from the commandline?

**Comment by cat2cat** [comment]
As you see below, I put netMHCpan under mhctools-master, why it still give me the following error?


And how should I build netMHCpan in the following folder?


DOCMM0AH563972:mhctools-master xhu$ ./netMHCpan-3.0/Linux_x86_64/bin/netMHCpan -f netMHCpan-3.0/data/

-bash: ./netMHCpan-3.0/Linux_x86_64/bin/netMHCpan: cannot execute binary file



Many thanks,


DOCMM0AH563972:mhctools-master xhu$ ls

LICENSE build mhctools netMHCpan-3.0 setup.py

README.md dist mhctools.egg-info pylintrc test

RELEASING.md lint.sh netMHCpan

requirements.txt


>>> from mhctools import NetMHCpan

>>> predictor = NetMHCpan(alleles=["A*02:01", "hla-a0101"])

Traceback (most recent call last):

  File "<stdin>", line 1, in <module>

  File "mhctools/netmhc_pan.py", line 43, in NetMHCpan

    stderr=devnull)

  File "/Users/xhu/miniconda2/lib/python2.7/subprocess.py", line 212, in check_output

    process = Popen(stdout=PIPE, *popenargs, **kwargs)

  File "/Users/xhu/miniconda2/lib/python2.7/subprocess.py", line 390, in __init__

    errread, errwrite)

  File "/Users/xhu/miniconda2/lib/python2.7/subprocess.py", line 1024, in _execute_child

    raise child_exception

OSError: [Errno 2] No such file or directory

**Comment by cat2cat** [comment]
Many thanks,.
netMHCpan is in my path, but why I am not able to run it? How should I built or set up netMHCpan?



DOCMM0AH563972:mhctools-master xhu$ ./netMHCpan-3.0/Linux_x86_64/bin/netMHCpan -f netMHCpan-3.0/data/

-bash: ./netMHCpan-3.0/Linux_x86_64/bin/netMHCpan: cannot execute binary file


>>> from mhctools import NetMHCpan

>>> predictor = NetMHCpan(alleles=["A*02:01", "hla-a0101"])

Traceback (most recent call last):

  File "<stdin>", line 1, in <module>

  File "mhctools/netmhc_pan.py", line 43, in NetMHCpan

    stderr=devnull)

  File "/Users/xhu/miniconda2/lib/python2.7/subprocess.py", line 212, in check_output

    process = Popen(stdout=PIPE, *popenargs, **kwargs)

  File "/Users/xhu/miniconda2/lib/python2.7/subprocess.py", line 390, in __init__

    errread, errwrite)

  File "/Users/xhu/miniconda2/lib/python2.7/subprocess.py", line 1024, in _execute_child

    raise child_exception

OSError: [Errno 2] No such file or directory

**Comment by cat2cat** [comment]
Yes how should I build and set netMHCpan correctly?



DOCMM0AH563972:mhctools-master xhu$ ./netMHCpan-3.0/Linux_x86_64/bin/netMHCpan -a

-bash: ./netMHCpan-3.0/Linux_x86_64/bin/netMHCpan: cannot execute binary file

**Comment by julia326** [comment]
Hi Kathy,

How did you install NetMHCpan, and what are the permissions on your NetMHCpan binary file? You should be able to run it as a standalone executable and get output like this:

```
admins-MacBook-Air:mhctools julia$ /Users/julia/code/bundle/bin/netMHCpan
# /Users/julia/code/bundle/netMHCpan-3.0/Darwin_x86_64/bin/netMHCpan
# Thu May 18 11:57:06 2017
# User: julia
# PWD : /Users/julia/code/mhctools
# Host: Darwin admins-MacBook-Air.local 15.6.0 x86_64
# Command line parameters set to:
#	[-rdir filename]     /Users/julia/code/bundle/netMHCpan-3.0/Darwin_x86_64 Home directory for NetMHpan
#	[-syn filename]      /Users/julia/code/bundle/netMHCpan-3.0/Darwin_x86_64/data/synlist Synaps file
#	[-v]                 0                    Verbose mode
#	[-dirty]             0                    Dirty mode, leave tmp dir+files
#	[-tdir filename]     /tmp/bundle/netMHCpanXXXXXX Temporary directory (made with mkdtemp)
#	[-hlapseudo filename] /Users/julia/code/bundle/netMHCpan-3.0/Darwin_x86_64/data/MHC_pseudo.dat File with HLA pseudo sequences
#	[-hlaseq filename]                        File with full length HLA sequences
#	[-a line]            HLA-A02:01           HLA allele
#	[-f filename]                             File name with input
#	[-w]                 0                    w option for webface
#	[-s]                 0                    Sort output on descending affinity
#	[-p]                 0                    Use peptide input
#	[-rth float]         0.500000             Rank Threshold for high binding peptides
#	[-rlt float]         2.000000             Rank Threshold for low binding peptides
#	[-l string]          8,9,10,11            Peptide length [8-11] (multiple length with ,)
#	[-xls]               0                    Save output to xls file
#	[-xlsfile filename]  NetMHCpan_out.xls    Filename for xls dump
#	[-t float]           -99.900002           Threshold for output
#	[-thrfmt filename]   /Users/julia/code/bundle/netMHCpan-3.0/Darwin_x86_64/data/threshold/%s.thr Format for threshold filenames
#	[-expfix]            0                    Exclude prefix from synlist
#	[-version filename]  /Users/julia/code/bundle/netMHCpan-3.0/Darwin_x86_64/data/version File with version information
#	[-inptype int]       0                    Input type [0] FASTA [1] Peptide
#	[-listMHC]           0                    Print list of alleles included in netMHCpan
#	[-allname filename]  /Users/julia/code/bundle/netMHCpan-3.0/Darwin_x86_64/data/allelenames File with print names for alleles
You most specify input file either by using -f or as /Users/julia/code/bundle/netMHCpan-3.0/Darwin_x86_64/bin/netMHCpan [args] fastafile
Usage: netMHCpan [-h] [args] [fastafile]
```

For now, try `ls -la /netMHCpan-3.0/Linux_x86_64/bin/netMHCpan`?

Cheers,
Julia
